[package]
name = "gust-diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Beautiful error formatting for Gust"

[dependencies]
miette.workspace = true
thiserror.workspace = true
console.workspace = true
